# 2.4- Data Preparation - Outliers, Normalization

Outliers, Normalization

In [1]:
import pandas as pd
import numpy as np

In [2]:
Train =  pd.read_csv("datasets/TrainEncoded.csv")
Test =  pd.read_csv("datasets/TestEncoded.csv")

In [3]:
Train.head()

,Rating,Reviews,Type,SizeNew,InstallsNew,PriceNew,LastUpdatedNewYear,LastUpdatedNewMonth,LastUpdatedNewDay,AndroidVerNew,...,Genres_Strategy;Education,Genres_Tools,Genres_Tools;Education,Genres_Travel & Local,Genres_Travel & Local;Action & Adventure,Genres_Trivia,Genres_Video Players & Editors,Genres_Video Players & Editors;Music & Video,Genres_Weather,Genres_Word
0,1.0,149723,0,0.041000,10000000,0.0,2018,6,13,4.000000,...,0,0,0,1,0,0,0,0,0,0
1,0.0,853,0,0.340000,100000,0.0,2018,3,22,4.100000,...,0,0,0,0,0,0,0,0,0,0
2,1.0,61881,0,0.372354,5000000,0.0,2018,4,10,3.831783,...,0,0,0,0,0,0,0,0,0,0
3,0.0,21943,0,0.023000,5000000,0.0,2016,10,19,2.300000,...,0,1,0,0,0,0,0,0,0,0
4,1.0,6,0,0.092000,1000,0.0,2018,1,24,4.100000,...,0,0,0,0,0,0,0,0,0,0

In [4]:
Train.shape

(5788, 125)

In [5]:
Test.head()

,Reviews,Type,SizeNew,InstallsNew,PriceNew,LastUpdatedNewYear,LastUpdatedNewMonth,LastUpdatedNewDay,AndroidVerNew,ReviewGroupNew,...,Genres_Strategy;Education,Genres_Tools,Genres_Tools;Education,Genres_Travel & Local,Genres_Travel & Local;Action & Adventure,Genres_Trivia,Genres_Video Players & Editors,Genres_Video Players & Editors;Music & Video,Genres_Weather,Genres_Word
0,10,0,0.030000,1000,0.0,2018,1,14,4.100000,0,...,0,0,0,0,0,0,0,0,0,0
1,7146,0,0.140000,1000000,0.0,2018,2,2,4.000000,2,...,0,0,0,0,0,0,0,0,0,0
2,2221,0,0.392887,100000,0.0,2018,7,10,3.837752,2,...,0,0,0,0,0,0,0,0,0,0
3,21,0,0.025000,100,0.0,2017,10,31,4.200000,0,...,0,0,0,0,0,0,0,0,0,0
4,2822,0,0.270000,100000,0.0,2018,7,27,4.100000,2,...,0,0,0,1,0,0,0,0,0,0

In [6]:
Test.shape

(1448, 124)

## Outliers

*Warning* - I tested oputliers, but finaally not used because of poor performance

In [7]:
class Outliers:
    def __init__(self, df):
        self.df = df
    
    ## function to find outliers limits
    def find_limits_and_delete_outliers(self, variable):

        IQR = self.df[variable].quantile(0.75) - self.df[variable].quantile(0.25)

        lower_limit = self.df[variable].quantile(0.25) - (IQR * 1.5)
        upper_limit = self.df[variable].quantile(0.75) + (IQR * 1.5)

        ## to find and delete values upper and under the outliers limits
        np.where(self.df[variable] > upper_limit)
        np.where(self.df[variable] < lower_limit)
        
        outliers = np.where(self.df[variable] > upper_limit, True, 
                            np.where(self.df[variable] < lower_limit, True, False))
        
        outliers_df = self.df.loc[outliers, variable]
        outliers_df_ids = self.df.loc[outliers]
        new_df = self.df.drop(outliers_df_ids.index).reset_index(drop=True)
        
        outliers_percentage = len(outliers_df) / len(self.df)
        
        return outliers_percentage, new_df

In [8]:
outliers_instance = Outliers(Train)

In [9]:
print(Train.columns.tolist())

['Rating', 'Reviews', 'Type', 'SizeNew', 'InstallsNew', 'PriceNew', 'LastUpdatedNewYear', 'LastUpdatedNewMonth', 'LastUpdatedNewDay', 'AndroidVerNew', 'ReviewGroupNew', 'Genres_Action', 'Genres_Action;Action & Adventure', 'Genres_Adventure', 'Genres_Adventure;Action & Adventure', 'Genres_Adventure;Brain Games', 'Genres_Adventure;Education', 'Genres_Arcade', 'Genres_Arcade;Action & Adventure', 'Genres_Art & Design', 'Genres_Art & Design;Action & Adventure', 'Genres_Art & Design;Creativity', 'Genres_Art & Design;Pretend Play', 'Genres_Auto & Vehicles', 'Genres_Beauty', 'Genres_Board', 'Genres_Board;Action & Adventure', 'Genres_Board;Brain Games', 'Genres_Board;Pretend Play', 'Genres_Books & Reference', 'Genres_Books & Reference;Creativity', 'Genres_Books & Reference;Education', 'Genres_Business', 'Genres_Card', 'Genres_Card;Action & Adventure', 'Genres_Casino', 'Genres_Casual', 'Genres_Casual;Action & Adventure', 'Genres_Casual;Brain Games', 'Genres_Casual;Creativity', 'Genres_Casual;Education', 'Genres_Casual;Music & Video', 'Genres_Casual;Pretend Play', 'Genres_Comics', 'Genres_Comics;Creativity', 'Genres_Communication', 'Genres_Dating', 'Genres_Education', 'Genres_Education;Action & Adventure', 'Genres_Education;Brain Games', 'Genres_Education;Creativity', 'Genres_Education;Education', 'Genres_Education;Music & Video', 'Genres_Education;Pretend Play', 'Genres_Educational', 'Genres_Educational;Action & Adventure', 'Genres_Educational;Brain Games', 'Genres_Educational;Creativity', 'Genres_Educational;Education', 'Genres_Educational;Pretend Play', 'Genres_Entertainment', 'Genres_Entertainment;Action & Adventure', 'Genres_Entertainment;Brain Games', 'Genres_Entertainment;Creativity', 'Genres_Entertainment;Education', 'Genres_Entertainment;Music & Video', 'Genres_Entertainment;Pretend Play', 'Genres_Events', 'Genres_Finance', 'Genres_Food & Drink', 'Genres_Health & Fitness', 'Genres_Health & Fitness;Action & Adventure', 'Genres_Health & Fitness;Education', 'Genres_House & Home', 'Genres_Libraries & Demo', 'Genres_Lifestyle', 'Genres_Lifestyle;Education', 'Genres_Lifestyle;Pretend Play', 'Genres_Maps & Navigation', 'Genres_Medical', 'Genres_Music', 'Genres_Music & Audio;Music & Video', 'Genres_Music;Music & Video', 'Genres_News & Magazines', 'Genres_Parenting', 'Genres_Parenting;Brain Games', 'Genres_Parenting;Education', 'Genres_Parenting;Music & Video', 'Genres_Personalization', 'Genres_Photography', 'Genres_Productivity', 'Genres_Puzzle', 'Genres_Puzzle;Action & Adventure', 'Genres_Puzzle;Brain Games', 'Genres_Puzzle;Creativity', 'Genres_Puzzle;Education', 'Genres_Racing', 'Genres_Racing;Action & Adventure', 'Genres_Racing;Pretend Play', 'Genres_Role Playing', 'Genres_Role Playing;Action & Adventure', 'Genres_Role Playing;Brain Games', 'Genres_Role Playing;Education', 'Genres_Role Playing;Pretend Play', 'Genres_Shopping', 'Genres_Simulation', 'Genres_Simulation;Action & Adventure', 'Genres_Simulation;Education', 'Genres_Simulation;Pretend Play', 'Genres_Social', 'Genres_Sports', 'Genres_Sports;Action & Adventure', 'Genres_Strategy', 'Genres_Strategy;Action & Adventure', 'Genres_Strategy;Creativity', 'Genres_Strategy;Education', 'Genres_Tools', 'Genres_Tools;Education', 'Genres_Travel & Local', 'Genres_Travel & Local;Action & Adventure', 'Genres_Trivia', 'Genres_Video Players & Editors', 'Genres_Video Players & Editors;Music & Video', 'Genres_Weather', 'Genres_Word']

In [10]:
columns = ['AndroidVerNew', 'InstallsNew', 'LastUpdatedNewDay', 'LastUpdatedNewMonth', 
           'LastUpdatedNewYear', 'PriceNew', 'ReviewGroupNew', 'Reviews', 'SizeNew', 'Type']

In [11]:
Train.shape

(5788, 125)

In [12]:
def removing_outliers(df, first_column, other_columns):
    outliers_instance = Outliers(df)
    outliers_percentage, new_df = outliers_instance.find_limits_and_delete_outliers(first_column)
    print(first_column, outliers_percentage, new_df.shape)
    
    for column in other_columns:
        outliers_instance = Outliers(new_df)
        outliers_percentage, new_df = outliers_instance.find_limits_and_delete_outliers(column)
        print(column, outliers_percentage, new_df.shape)
    return outliers_percentage, new_df

In [13]:
outliers_percentage, new_df = removing_outliers(Train, columns[0], columns[1:])

AndroidVerNew 0.24619903248099517 (4363, 125)
InstallsNew 0.2218656887462755 (3395, 125)
LastUpdatedNewDay 0.0 (3395, 125)
LastUpdatedNewMonth 0.0 (3395, 125)
LastUpdatedNewYear 0.03622974963181149 (3272, 125)
PriceNew 0.0776283618581907 (3018, 125)
ReviewGroupNew 0.0 (3018, 125)
Reviews 0.16401590457256462 (2523, 125)
SizeNew 0.04003170828378914 (2422, 125)
Type 0.0 (2422, 125)

In [14]:
new_df.shape

(2422, 125)

In [15]:
new_df['Rating'].value_counts()

1.0    1747
0.0     675
Name: Rating, dtype: int64

## Normalization

In [16]:
## Normalization
from sklearn.preprocessing import StandardScaler

In [17]:
class Normalization:
    def __init__(self, df):
        self.df = df
        
    def normalization(self, columns):
        scaler = StandardScaler()

        ## features to normalice
        normalice = self.df[columns]
        scaler.fit(normalice)
        df_scaled = scaler.transform(normalice)
        
        new_columns = [str(x)+'_scaled' for x in columns]
        
        df_scaled = pd.DataFrame(df_scaled, columns=new_columns)
        self.df = pd.concat([self.df,df_scaled], axis=1)
        
        self.df = self.df.drop(columns, axis=1)
        return self.df
    
    # Final dataframe
    def final_dataframe(self):
        return self.df

In [18]:
norm_instance_train = Normalization(new_df)

In [19]:
print(new_df.columns.tolist())

['Rating', 'Reviews', 'Type', 'SizeNew', 'InstallsNew', 'PriceNew', 'LastUpdatedNewYear', 'LastUpdatedNewMonth', 'LastUpdatedNewDay', 'AndroidVerNew', 'ReviewGroupNew', 'Genres_Action', 'Genres_Action;Action & Adventure', 'Genres_Adventure', 'Genres_Adventure;Action & Adventure', 'Genres_Adventure;Brain Games', 'Genres_Adventure;Education', 'Genres_Arcade', 'Genres_Arcade;Action & Adventure', 'Genres_Art & Design', 'Genres_Art & Design;Action & Adventure', 'Genres_Art & Design;Creativity', 'Genres_Art & Design;Pretend Play', 'Genres_Auto & Vehicles', 'Genres_Beauty', 'Genres_Board', 'Genres_Board;Action & Adventure', 'Genres_Board;Brain Games', 'Genres_Board;Pretend Play', 'Genres_Books & Reference', 'Genres_Books & Reference;Creativity', 'Genres_Books & Reference;Education', 'Genres_Business', 'Genres_Card', 'Genres_Card;Action & Adventure', 'Genres_Casino', 'Genres_Casual', 'Genres_Casual;Action & Adventure', 'Genres_Casual;Brain Games', 'Genres_Casual;Creativity', 'Genres_Casual;Education', 'Genres_Casual;Music & Video', 'Genres_Casual;Pretend Play', 'Genres_Comics', 'Genres_Comics;Creativity', 'Genres_Communication', 'Genres_Dating', 'Genres_Education', 'Genres_Education;Action & Adventure', 'Genres_Education;Brain Games', 'Genres_Education;Creativity', 'Genres_Education;Education', 'Genres_Education;Music & Video', 'Genres_Education;Pretend Play', 'Genres_Educational', 'Genres_Educational;Action & Adventure', 'Genres_Educational;Brain Games', 'Genres_Educational;Creativity', 'Genres_Educational;Education', 'Genres_Educational;Pretend Play', 'Genres_Entertainment', 'Genres_Entertainment;Action & Adventure', 'Genres_Entertainment;Brain Games', 'Genres_Entertainment;Creativity', 'Genres_Entertainment;Education', 'Genres_Entertainment;Music & Video', 'Genres_Entertainment;Pretend Play', 'Genres_Events', 'Genres_Finance', 'Genres_Food & Drink', 'Genres_Health & Fitness', 'Genres_Health & Fitness;Action & Adventure', 'Genres_Health & Fitness;Education', 'Genres_House & Home', 'Genres_Libraries & Demo', 'Genres_Lifestyle', 'Genres_Lifestyle;Education', 'Genres_Lifestyle;Pretend Play', 'Genres_Maps & Navigation', 'Genres_Medical', 'Genres_Music', 'Genres_Music & Audio;Music & Video', 'Genres_Music;Music & Video', 'Genres_News & Magazines', 'Genres_Parenting', 'Genres_Parenting;Brain Games', 'Genres_Parenting;Education', 'Genres_Parenting;Music & Video', 'Genres_Personalization', 'Genres_Photography', 'Genres_Productivity', 'Genres_Puzzle', 'Genres_Puzzle;Action & Adventure', 'Genres_Puzzle;Brain Games', 'Genres_Puzzle;Creativity', 'Genres_Puzzle;Education', 'Genres_Racing', 'Genres_Racing;Action & Adventure', 'Genres_Racing;Pretend Play', 'Genres_Role Playing', 'Genres_Role Playing;Action & Adventure', 'Genres_Role Playing;Brain Games', 'Genres_Role Playing;Education', 'Genres_Role Playing;Pretend Play', 'Genres_Shopping', 'Genres_Simulation', 'Genres_Simulation;Action & Adventure', 'Genres_Simulation;Education', 'Genres_Simulation;Pretend Play', 'Genres_Social', 'Genres_Sports', 'Genres_Sports;Action & Adventure', 'Genres_Strategy', 'Genres_Strategy;Action & Adventure', 'Genres_Strategy;Creativity', 'Genres_Strategy;Education', 'Genres_Tools', 'Genres_Tools;Education', 'Genres_Travel & Local', 'Genres_Travel & Local;Action & Adventure', 'Genres_Trivia', 'Genres_Video Players & Editors', 'Genres_Video Players & Editors;Music & Video', 'Genres_Weather', 'Genres_Word']

In [20]:
columns = ['AndroidVerNew', 'InstallsNew', 'LastUpdatedNewDay', 'LastUpdatedNewMonth', 
           'LastUpdatedNewYear', 'PriceNew', 'ReviewGroupNew', 'Reviews', 'SizeNew']

In [21]:
norm_instance_train.normalization(columns).head()

,Rating,Type,Genres_Action,Genres_Action;Action & Adventure,Genres_Adventure,Genres_Adventure;Action & Adventure,Genres_Adventure;Brain Games,Genres_Adventure;Education,Genres_Arcade,Genres_Arcade;Action & Adventure,...,Genres_Word,AndroidVerNew_scaled,InstallsNew_scaled,LastUpdatedNewDay_scaled,LastUpdatedNewMonth_scaled,LastUpdatedNewYear_scaled,PriceNew_scaled,ReviewGroupNew_scaled,Reviews_scaled,SizeNew_scaled
0,0.0,0,0,0,0,0,0,0,0,0,...,0,0.023680,-0.117559,0.660164,-1.102048,0.609744,0.0,0.139689,-0.180101,1.172677
1,1.0,0,0,0,0,0,0,0,0,0,...,0,0.023680,-0.472895,0.880446,-1.826281,0.609744,0.0,-1.104158,-0.511544,-0.521467
2,1.0,0,0,0,0,0,0,0,0,0,...,0,-0.668864,-0.472895,1.210870,-1.102048,0.609744,0.0,-1.104158,-0.508804,-0.842535
3,1.0,0,0,0,0,0,0,0,0,0,...,0,-0.668864,-0.472895,0.439882,-1.826281,0.609744,0.0,-1.104158,-0.511935,0.011369
4,1.0,0,0,0,0,0,0,0,0,0,...,0,-0.668864,-0.440592,0.439882,-1.826281,0.609744,0.0,0.139689,-0.475934,-0.972328

In [22]:
norm_instance_train.final_dataframe().head()

,Rating,Type,Genres_Action,Genres_Action;Action & Adventure,Genres_Adventure,Genres_Adventure;Action & Adventure,Genres_Adventure;Brain Games,Genres_Adventure;Education,Genres_Arcade,Genres_Arcade;Action & Adventure,...,Genres_Word,AndroidVerNew_scaled,InstallsNew_scaled,LastUpdatedNewDay_scaled,LastUpdatedNewMonth_scaled,LastUpdatedNewYear_scaled,PriceNew_scaled,ReviewGroupNew_scaled,Reviews_scaled,SizeNew_scaled
0,0.0,0,0,0,0,0,0,0,0,0,...,0,0.023680,-0.117559,0.660164,-1.102048,0.609744,0.0,0.139689,-0.180101,1.172677
1,1.0,0,0,0,0,0,0,0,0,0,...,0,0.023680,-0.472895,0.880446,-1.826281,0.609744,0.0,-1.104158,-0.511544,-0.521467
2,1.0,0,0,0,0,0,0,0,0,0,...,0,-0.668864,-0.472895,1.210870,-1.102048,0.609744,0.0,-1.104158,-0.508804,-0.842535
3,1.0,0,0,0,0,0,0,0,0,0,...,0,-0.668864,-0.472895,0.439882,-1.826281,0.609744,0.0,-1.104158,-0.511935,0.011369
4,1.0,0,0,0,0,0,0,0,0,0,...,0,-0.668864,-0.440592,0.439882,-1.826281,0.609744,0.0,0.139689,-0.475934,-0.972328

In [23]:
norm_instance_test = Normalization(Test)

In [24]:
norm_instance_test.normalization(columns).head()

,Type,Genres_Action,Genres_Action;Action & Adventure,Genres_Adventure,Genres_Adventure;Action & Adventure,Genres_Adventure;Brain Games,Genres_Adventure;Education,Genres_Arcade,Genres_Arcade;Action & Adventure,Genres_Art & Design,...,Genres_Word,AndroidVerNew_scaled,InstallsNew_scaled,LastUpdatedNewDay_scaled,LastUpdatedNewMonth_scaled,LastUpdatedNewYear_scaled,PriceNew_scaled,ReviewGroupNew_scaled,Reviews_scaled,SizeNew_scaled
0,0,0,0,0,0,0,0,0,0,0,...,0,3.313342e-01,-0.155567,-0.181475,-2.054276,0.577520,-0.055663,-1.408071,-0.213475,-3.643848e-01
1,0,0,0,0,0,0,0,0,0,0,...,0,2.049904e-01,-0.133841,-1.451947,-1.673357,0.577520,-0.055663,0.378076,-0.204553,-2.539308e-01
2,0,0,0,0,0,0,0,0,0,0,...,0,1.122158e-15,-0.153414,-0.604966,0.231234,0.577520,-0.055663,0.378076,-0.210711,5.574025e-17
3,0,0,0,0,0,0,0,0,0,0,...,0,4.576780e-01,-0.155586,1.618360,1.373989,-0.311161,-0.055663,-1.408071,-0.213461,-3.694054e-01
4,0,0,0,0,0,0,0,0,0,0,...,0,3.313342e-01,-0.153414,1.194870,0.231234,0.577520,-0.055663,0.378076,-0.209959,-1.233943e-01

In [25]:
norm_instance_train.final_dataframe().to_csv("datasets/TrainOutliersNormalization.csv", index=False)

norm_instance_test.final_dataframe().to_csv("datasets/TestOutliersNormalization.csv", index=False)